##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
    web:
        container_name: magento2devbox_web_c34677f3da19131a5906e3eebf672dc4
        restart: always
        image: magento/magento2devbox-web:latest
        volumes:
          - "./shared/webroot:/home/magento2/magento2"
          - "~/.composer:/home/magento2/.composer"
          - "~/.ssh:/home/magento2/.ssh"
          - "./shared/logs/apache2:/var/log/apache2"
          - "./shared/logs/php-fpm:/var/log/php-fpm"
          - "./shared/.magento-cloud:/home/magento2/.magento-cloud"
        environment:
          - USE_SHARED_WEBROOT=0
          - SHARED_CODE_PATH="/home/magento2/magento2"
          - USE_RABBITMQ=0
          - USE_REDIS_FULL_PAGE_CACHE=0
          - USE_REDIS_CACHE=1
          - USE_REDIS_SESSIONS=1
          - USE_VARNISH=1
          - USE_ELASTICSEARCH=1
          - MAGENTO_PUBLIC_KEY=348d2dc2c062da3156cf49f78e4fc975
          - MAGENTO_PRIVATE_KEY=ff9bfca586d921f427ba4156961d9152
          - MAGENTO_USE_SOURCES_IN_HOST=0
          - CREATE_SYMLINK_EE=0
          - HOST_CE_PATH=./shared/webroot
          - EE_DIRNAME=magento2ee
          - MAGENTO_DOWNLOAD_SOURCES_COMPOSER=1
          - MAGENTO_EDITION=ce
          - MAGENTO_VERSION=2.1.5
          - MAGENTO_SAMPLE_DATA_INSTALL=0
          - MAGENTO_DOWNLOAD_SOURCES_CLOUD=0
          - MCLOUD_USERNAME=
          - MCLOUD_PASSWORD=
          - MCLOUD_GENERATE_NEW_TOKEN=
          - MCLOUD_PROJECT=
          - MCLOUD_BRANCH=
          - MAGENTO_CRON_RUN=0
          - MAGENTO_DI_COMPILE=0
          - MAGENTO_GRUNT_COMPILE=0
          - MAGENTO_STATIC_CONTENTS_DEPLOY=0
          - MAGENTO_BACKEND_PATH=admin
          - MAGENTO_ADMIN_USER=admin
          - MAGENTO_ADMIN_PASSWORD=admin123
        ports:
          - "80"
          - "22"

    db:
        container_name: magento2devbox_db_c34677f3da19131a5906e3eebf672dc4
        restart: always
        image: mysql:5.6
        ports:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento2
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

    varnish:
        container_name: magento2devbox_varnish_c34677f3da19131a5906e3eebf672dc4
        restart: always
        depends_on:
          - "web"
        image: magento/magento2devbox-varnish:latest
        ports:
          - "6081"

    redis:
        container_name: magento2devbox_redis_c34677f3da19131a5906e3eebf672dc4
        restart: always
        image: redis:3.0.7

    elasticsearch:
        container_name: magento2devbox_elastic_c34677f3da19131a5906e3eebf672dc4
        restart: always
        image: elasticsearch:2
        ports:
          - "9200"

